//
//  genMaze.h
//  MazeProject
//
//  Created by Mohit Jain on 10/19/17.
//  Copyright © 2017 Mohit Jain. All rights reserved.
//

#ifndef _GEN_MAZE_H_
#define _GEN_MAZE_H_

#include <stdio.h>
#include <stdlib.h>
#include <time.h>

/*
 * typedef struct cell
 *
 * Each cell consists of four components of type unsigned char,
 * north, east, south, and west. Each component will be either
 * 0 or 1 after the maze is generated by the genMaze() function.
 * If the north component is 0, it means that there is no wall
 * in the north direction of that cell. If the north component is
 * 1, there is a wall in the north direction. Meaning are the same
 * for east, south, and west components.
 */
typedef struct
{
    unsigned char north;
    unsigned char east;
    unsigned char south;
    unsigned char west;
} cell;


int get_num_walls(int numRows, int numColumns, cell *cells);
int print_maze(int numRows, int numColumns, cell *cells);
void gen_maze(int numRows, int numColumns, cell *cells);

#endif
